#!/bin/sh

NAME=Cambio_NodeJS
PIDFILE=/var/run/$NAME.pid
LOGFILE=/var/log/$NAME.log
APP_DIR="/www/server/server"
APP_DIR="/opt/server"
NODE_APP="server.js"
DAEMON=$(which node)
OPTS="$APP_DIR/$NODE_APP"


    

# Sanity checks
test -f $CONFFILE || exit 0

if [ ! -d $PIDDIR ]
then
  mkdir -p $PIDDIR
fi

if [ ! -x $DAEMON ]; then
  echo "ERROR: Can't locate $DAEMON."
  exit 1
fi

get_pid() {
    if [ -f "$PIDFILE" ]; then
        cat "$PIDFILE"
    else
        echo "No PID yet"
    fi
}

is_running() {
    [ -f "$PIDFILE" ]
}

start() {
        printf "Starting $NAME: "
        export NODE_ENV=$NODE_ENVIROMENT
        cd $APP_DIR
        start-stop-daemon -S -q -b -m -p $PIDFILE --exec $DAEMON -- $OPTS
        case "$?" in
        0)
            echo "$NAME started (`get_pid`)"
            exit 0
        ;;
        1)
            echo "$NAME seems to be running (`get_pid`)"
        ;;
        2)
            echo "This is really strange [2]"
        ;;
        3)
            echo "ERROR: $NAME did not start"
        ;;
        *)
            echo "This is really strange [???]"
    esac
    exit 1
}

stop() {
        printf "Stopping $NAME: "
        start-stop-daemon --stop --quiet --pidfile $PIDFILE \
                && echo "OK" || echo "FAIL"
}

status() {
    if is_running; then
        PID=$(get_pid)
        echo "$NAME is running with pid $PIDFILE : $(get_pid)"
    else
        echo "$NAME is stopped, but pid file exists"
    fi
}

case "$1" in
        start)
                start
                ;;
        stop)
                stop
                ;;
        restart|reload)
                stop
                sleep 1
                start
                ;;
        status)
                status
                ;;
        *)
                echo "Usage: $0 {start|stop|restart}"
                exit 1
esac