#!/bin/sh
NAME=mpd
PIDFILE=/var/run/mpd/mpd.pid
CONFFILE=/opt/mpd/mpd.conf

# Sanity checks
test -f /opt/mpd/mpd.conf || exit 0

pid_file_exists() {
    [ -f "$PIDFILE" ]
}

get_pid() {
    echo "$(cat "$PIDFILE")"
}

is_running() {
    PID="$(get_pid)"
    [ -d /proc/$PID ]
}

start() {
        printf "Starting mpd: "
        start-stop-daemon -S -q -m -b -p $PIDFILE --exec /usr/bin/mpd -- $CONFFILE
        # start-stop-daemon -S -v -m -p /var/run/mpd/mpd.pid --exec /usr/bin/mpd -- /opt/mpd/mpd.conf
        if pid_file_exists
        then
            if is_running
            then
                PID=$(get_pid)
                echo "$NAME is running with pid $PIDFILE : $(get_pid)"
            else
                echo "$NAME is stopped, but pid file exists"
            fi
        else
            echo "$NAME is stopped"
        fi
}

stop() {
        printf "Stopping mpd: "
        start-stop-daemon --stop --quiet --pidfile $PIDFILE \
                && echo "OK" || echo "FAIL"
}

status() {
    if pid_file_exists
    then
        if is_running
        then
            PID=$(get_pid)
            echo "$NAME is running with pid $PIDFILE : $(get_pid)"
        else
            echo "$NAME is stopped, but pid file exists"
        fi
    else
        echo "$NAME is stopped"
    fi
}

case "$1" in
        start)
                start
                ;;
        stop)
                stop
                ;;
        restart|reload)
                stop
                sleep 1
                start
                ;;
        status)
                status
                ;;
        *)
                echo "Usage: $0 {start|stop|restart}"
                exit 1
esac