#!/bin/sh

NAME=raat_app
PIDFILE=/var/run/$NAME.pid
DAEMON=/opt/roon/$NAME
DAEMON_ARGS="/opt/roon/config.json"

start() {
        printf "Starting $NAME: "
        start-stop-daemon -S -q -m -b -p $PIDFILE --exec $DAEMON -- $DAEMON_ARGS
        [ $? = 0 ] && echo "OK" || echo "FAIL"
}
stop() {
        printf "Stopping $NAME: "
        start-stop-daemon -K -q -p $PIDFILE
        [ $? = 0 ] && echo "OK" || echo "FAIL"
}
restart() {
        stop
		sleep 2
        start
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        restart
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?