#!/bin/sh

NAME=Cambio_NodeJS
PIDFILE=/var/run/$NAME.pid
LOGFILE=/var/log/$NAME.log
APP_DIR="/www/server/server"
NODE_APP="server.js"
DAEMON=$(which node)
DAEMON_ARGS="/www/server/server/server.js"

pid_file_exists() {
    [ -f "$PIDFILE" ]
}

get_pid() {
    echo "$(cat "$PIDFILE")"
}

is_running() {
    PID="$(get_pid)"
    [ -d /proc/$PID ]
}

start() {
    export NODE_ENV=$NODE_ENVIROMENT
    printf "Starting $NAME: "
    start-stop-daemon -S -q -m -b -p $PIDFILE --exec $DAEMON -- $DAEMON_ARGS
    [ $? = 0 ] && echo "OK, started with pid $PIDFILE : $(get_pid)" || echo "FAIL"
}
stop() {
    printf "Stopping $NAME: "
    start-stop-daemon -K -q -p $PIDFILE
    [ $? = 0 ] && echo "OK" || echo "FAIL"
}
restart() {
    stop
    sleep 2
    start
}
status() {
    if pid_file_exists
    then
        if is_running
        then
            PID=$(get_pid)
            echo "$NAME is running with pid $PIDFILE : $(get_pid)"
        else
            echo "$NAME is stopped, but pid file exists"
        fi
    else
        echo "$NAME is stopped"
    fi
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        restart
        ;;
  status)
        status
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?